baseURL = "https://hueralin.github.io"
languageCode = "en-us"
title = "狐耳的雪原"
theme = "LeaveIt"

paginate = 12
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = ""

preserveTaxonomyNames = true

[blackfriday]
  hrefTargetBlank = true
  nofollowLinks = true
  noreferrerLinks = true

[Permalinks]
 posts = "/:year/:filename/"

# 分类
[taxonomy] 
  tag = "tags"
  categories = "categories"

# 自定义菜单
[menu]
  [[menu.main]]
    name = "博客"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 2

  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    name = "收藏"
    url = "/collect/"
    weight = 4

  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 5

# 友情链接
[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"
[[params.links]]
  title = "常用开发工具CDN镜像"
  name = "常用开发工具CDN镜像"
  url = "http://mirrors.flysnow.org/"

[params]
    since = 2011
    author = "狐耳"                           # Author's name
    avatar = "/img/huer.jpeg"           # Author's avatar
    subtitle = "好冷，储备点儿知识，准备度过互联网寒冬～"         # Subtitle
    cdn_url = ""           # Base CDN URL
    home_mode = "" # post or other

    google_verification = ""
   
    description = "" # site description
    keywords = "" # site keywords

    beian = ""
    baiduAnalytics = ""

    license= '本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议</a>进行许可'

# 社交账号
[params.social]
    GitHub = "hueralin"
    Email   = "1612415787@qq.com"
    Wechat = "/images/me/wechat.png"  # Wechat QRcode image

